### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' (Plotting DoS)

### ISSUE THREAD

**Issue by OkiPVP** [SMTG-Bham/sumo#245]
Dear all,

I tried to get the DoS of a chiral system of 2D-perovskite. Usually, I have errors in SUMO when 2 things occurs.
1_ The selected palette has no enough colours for plotting.
2_ The system presented a convergence error and thus the vasprun.xml file is not valid.

This time I had an error and thought it was problem 2. But I can plot the DoS in p4vasp. Therefore, I would like to know if you could help me to solve this issue. Here I attach a screenshot of the error.

![image](https://github.com/SMTG-Bham/sumo/assets/70239417/96c16f84-2b21-46fc-aa95-252d87985198)

Thanks

**Comment by ajjackson** [comment]
It looks like the Pymatgen importer for the Vasprun file is trying to guess where the POTCARs would be, found _something_ that didn't match the format and then raised an error.

It looks like you have an older version of the Pymatgen code, which was [tweaked five months ago](https://github.com/materialsproject/pymatgen/commit/181c365526c2c605a1f48d429767239dc16a43ab). Can you try updating to a newer version of Pymatgen and see how that affects things?

**Comment by OkiPVP** [comment]
Dear ajjackson,

Thank you very much for your reply. Unfortunately, after updating pymatgen, nothing works anymore. I have attached the error.
Reinstalling SUMO is not solving the problem either.

![image](https://github.com/SMTG-Bham/sumo/assets/70239417/67993d87-8ef4-4003-bf39-17d97263b13d)

**Comment by ajjackson** [comment]
Ah, I was wondering how long it would be before something like that came along. The problem here is that `castepbinx`, which Sumo relies on, refuses to install with Numpy version 2 or higher. (A sensible precaution as this indicates unknown (at time of coding) API changes.) Numpy 2 released a few days ago, so it is unlikely you are using any packages that _need_ it. Can you try `pip install numpy==1.26.4 sumo` to reinstall sumo and its dependencies alongside the last compatible version of Numpy?

(This sort of thing _should_ Just Work but it can get a bit messy after a few installations/uninstallations in the same environment.)

**Comment by ajjackson** [comment]
This still looks like an installation problem of some kind.

In a fresh Conda environment with only Python installed, I was able to `pip install sumo` and the dependencies resolved correctly (including the older Numpy).

It's very weird to me that a dependency version conflict could appear at runtime (rather than install time), but seemingly not unusual: https://stackoverflow.com/questions/52982603/python-entry-point-fails-for-dependency-conflict

Somehow your Python environment is convinced that there is still a version conflict. Without knowing why it thinks Numpy 2.0 is required, I'm not sure how to fix that; I don't think Sumo is the issue.

Can you try installing Sumo into a virtualenv and running from there?

**Comment by OkiPVP** [comment]
Problem solved. 
I just uninstalled SUMO, updated pip, matplotlib, rebooted, installed SUMO again and now everything works!!

Best
